### ISSUE TITLE
Goad is crashing...

### ISSUE THREAD

**Issue by runningman84** [goadapp/goad#175]
Sometimes goad (v 2.0.4) crashes during a test execution:

```
                                                                                goroutine 166 [chan send]:
                                                                                                          github.com/goadapp/goad/goad.Start.func1(0xe4d840, 0xc420340de0, 0xc420023500)
                              	/home/travis/gopath/src/github.com/goadapp/goad/goad/goad.go:29 +0xab
                                                                                                     created by github.com/goadapp/goad/goad.Start
                                                                                                                                                  	/home/travis/gopath/src/github.com/goadapp/goad/goad/goad.go:32 +0x107

                                                                    goroutine 167 [runnable]:
                                                                                             github.com/goadapp/goad/vendor/github.com/nsf/termbox-go.Init.func1()
        	/home/travis/gopath/src/github.com/goadapp/goad/vendor/github.com/nsf/termbox-go/api.go:87 +0x3fd
                                                                                                                 created by github.com/goadapp/goad/vendor/github.com/nsf/termbox-go.Init
                               	/home/travis/gopath/src/github.com/goadapp/goad/vendor/github.com/nsf/termbox-go/api.go:106 +0x5d9

                                                                                                                                  goroutine 168 [select]:
                                                                                                                                                         github.com/goadapp/goad/vendor/github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
                                                                                                         	/home/travis/gopath/src/github.com/goadapp/goad/vendor/github.com/nsf/termbox-go/api.go:321 +0x61e
                                                        github.com/goadapp/goad/cli.start.func1(0xc42022bd40)
                                                                                                             	/home/travis/gopath/src/github.com/goadapp/goad/cli/cli.go:312 +0x34
                          created by github.com/goadapp/goad/cli.start
                                                                      	/home/travis/gopath/src/github.com/goadapp/goad/cli/cli.go:317 +0x758

                                                                                                                                             goroutine 173 [chan send]:
             github.com/goadapp/goad/infrastructure/aws.(*AwsInfrastructure).Receive(0xc420340de0, 0xc42089d4a0)
                                                                                                                	/home/travis/gopath/src/github.com/goadapp/goad/infrastructure/aws/aws.go:70 +0x180
                                                 created by github.com/goadapp/goad/infrastructure.Aggregate
                                                                                                            	/home/travis/gopath/src/github.com/goadapp/goad/infrastructure/infrastructure.go:71 +0x6b
```

The shell is messed up afterwards.

**Comment by devops-eatigo** [comment]
We faced same issue here, it happens from time to time, especially when setting concurrent request number to a large amount. Any help?

**Comment by devops-eatigo** [comment]
There was one time we caught this:
fatal error: concurrent map iteration and map write
following by messy output like the post here
