### ISSUE TITLE
Runtime node no longer supported

### ISSUE THREAD

**Issue by alajusticia** [goadapp/goad#192]
Hi,

I've just installed the latest release (2.0.4) and I still have the error:
panic: InvalidParameterValueException: The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions.

**Comment by cjwilburn** [comment]
It looks like the [latest release](https://github.com/goadapp/goad/releases) is not up-to-date with the latest changes in the code. The latest release was in the fall of 2017, and the code appears to have been updated to fix this error 2 months ago. My _guess_ is that the best solution is to compile it from the source code, but even that is a chore because the base version of Go this runs on isn't very readily available.

**Comment by technion** [comment]
@cjwilburn  I'm not convinced this was properly fixed. I've finally managed to make a new build from master.

$ ./goad-2  -V
2.0.0-rc1x-612187f4

It's still errorring out:

```
panic: InvalidParameterValueException: The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions.
        status code: 400, request id: 89939126-81d4-11e9-9570-b31c2bafca23
```

This older version runs fine:

$ ./goad -V
2.0.0-rc1x-8fb30588

This seems to be an introduced issue.

**Comment by jay-dee7** [comment]
Issue is still not fixed, we tried to use for one of our projects and now it says

`panic: InvalidParameterValueException: The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs10.x) while creating or updating functions.
	status code: 400, request id: dc380806-021c-49de-a8c2-644b5cb8f87c
`

@matiaskorhonen  can i raise a pull request for it?

**Comment by pathcl** [comment]
I just compiled from source and it worked @jay-dee7

**Comment by vi8rel** [comment]
Fetching the project throws the following error

$ go get github.com/goadapp/goad

github.com/goadapp/goad/infrastructure/docker
src/github.com/goadapp/goad/infrastructure/docker/docker.go:303:25: undefined: infrastructure.Asset

github.com/goadapp/goad/infrastructure/aws
src/github.com/goadapp/goad/infrastructure/aws/aws.go:130:27: undefined: infrastructure.Asset

Compiling the app does not throw any error, however there is an error while trying to run the app 

panic: InvalidParameterValueException: The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs10.x) while creating or updating functions.
	status code: 400, request id: 70a9c73e-ac04-4907-b976-a2735e4df9d6

goroutine 1 [running]:
github.com/goadapp/goad/goad.HandleErr(0x23b4c40, 0xc420398000)
	/private/tmp/goad-20180822-38430-1yc3q9t/src/github.com/goadapp/goad/goad/goad.go:39 +0x4a
github.com/goadapp/goad/goad.Start(0xc4200f4180, 0x1052a00, 0xc420080c00)
	/private/tmp/goad-20180822-38430-1yc3q9t/src/github.com/goadapp/goad/goad/goad.go:21 +0x7e
github.com/goadapp/goad/cli.start(0xc4200f4180, 0xc420284f60, 0x0, 0x0, 0x0)
	/private/tmp/goad-20180822-38430-1yc3q9t/src/github.com/goadapp/goad/cli/cli.go:288 +0x6e
github.com/goadapp/goad/cli.Run()
	/private/tmp/goad-20180822-38430-1yc3q9t/src/github.com/goadapp/goad/cli/cli.go:89 +0x1bb
main.main()
	/private/tmp/goad-20180822-38430-1yc3q9t/src/github.com/goadapp/goad/main.go:6 +0x20

Any idea how to fix the nodejs runtime issue?

Tks

**Comment by vi8rel** [comment]
Here is the version of the app

$ goad -V
2.0.0-rc1x-e015a55f

**Comment by pathcl** [comment]
@vi8rel what worked for me was:

go get github.com/aws/aws-sdk-go
go get github.com/goadapp/goad
go get -u github.com/jteeuwen/go-bindata/...


Then depending on your operating system choose one (linux32,linux64,osx64,win64) like this:

make osx64

You have to do that where the repo was dowloaded usually $HOME/go/src/github.com/goadapp/goad

Then you will find a binary 'goad' in 'build' folder

**Comment by vi8rel** [comment]
@pathcl thank you for pointing me in the right direction.

Now it is not clear what is the syntax to insert an http POST body such as {"timestamp": "20190510", "geotag": "000000110000011100000011", "Event": "0001"}

./goad -n 5000 -c 1000 -H "Content-type: application/json" -m "POST" --body="timestamp: 20190510, geotag: 000000110000011100000011, Event: 0200" "http://test.site.com/path" 

returns 502 bad gateway response (output below)

   TotReqs   TotBytes    AvgTime    AvgReq/s  (post)unzip
     10000     1.7 MB     0.043s    26876.71     4.6 MB/s
   Slowest    Fastest   Timeouts  TotErrors
    0.752s     0.002s          0      10000
HTTPStatus   Requests
       502      10000

A simple curl command works just fine and returns a 200 OK response 

curl -H "content-type: application/json" -X POST -d '{"timestamp": "20190510", "geotag": "000000110000011100000011", "Event": "0200"}' http://test.site.com/path

**Comment by pathcl** [comment]
I just tested against httpbin.org/post and its giving me 200:
```
amsmac011:x86-64 pathcl$ ./goad -n 10 -c 10 -H "Content-type: application/json" -m "POST" --body='{"key1":"value1", "key2":"value2"}' http://httpbin.org/post
Regional results

Region: ap-northeast-1
   TotReqs   TotBytes    AvgTime    AvgReq/s  (post)unzip
         4     1.1 kB     0.019s      141.82      40 kB/s
   Slowest    Fastest   Timeouts  TotErrors
    0.026s     0.002s          0          0
Region: eu-west-1
   TotReqs   TotBytes    AvgTime    AvgReq/s  (post)unzip
         3      858 B     0.017s      156.36      45 kB/s
   Slowest    Fastest   Timeouts  TotErrors
    0.019s     0.014s          0          0
Region: us-east-1
   TotReqs   TotBytes    AvgTime    AvgReq/s  (post)unzip
         3      861 B     0.008s      345.57      99 kB/s
   Slowest    Fastest   Timeouts  TotErrors
    0.010s     0.005s          0          0

Overall

   TotReqs   TotBytes    AvgTime    AvgReq/s  (post)unzip
        10     2.9 kB     0.015s      643.75     184 kB/s
   Slowest    Fastest   Timeouts  TotErrors
    0.026s     0.002s          0          0
HTTPStatus   Requests
       200         10

```

**Comment by Botono** [comment]
@pathcl I followed your steps to build from source, but I'm still getting the "The runtime parameter of nodejs8.10 is no longer supported" error.

```
goad -V
2.0.0-rc1x-612187f4
```

Has this project been abandoned?

**Comment by pathcl** [comment]
It looks indeed abandoned but I can give you a hand tomorrow

**Comment by Botono** [comment]
@pathcl I got it working, and opened a PR for the fix: #202
