### ISSUE TITLE
Error panic: NoCredentialProviders:

### ISSUE THREAD

**Issue by grulles** [goadapp/goad#195]
Hi,
When I launched GOAD on my linux box I got this message:
./goad 
panic: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

goroutine 1 [running]:
github.com/goadapp/goad/goad.HandleErr(0x7f8a71594290, 0xc42001a880)
        /home/travis/gopath/src/github.com/goadapp/goad/goad/goad.go:39 +0x4a
github.com/goadapp/goad/goad.Start(0xc42009a540, 0x406b67, 0xc420207da0)
        /home/travis/gopath/src/github.com/goadapp/goad/goad/goad.go:21 +0x7e
github.com/goadapp/goad/cli.start(0xc42009a540, 0xc420207d40, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/goadapp/goad/cli/cli.go:288 +0x8b
github.com/goadapp/goad/cli.Run()
        /home/travis/gopath/src/github.com/goadapp/goad/cli/cli.go:89 +0x1f8
main.main()
        /home/travis/gopath/src/github.com/goadapp/goad/main.go:6 +0x20

How can I resolve this issue? 
thank you,

**Comment by t0t07** [comment]
Make sure you have aws credentials
https://github.com/goadapp/goad#aws-credentials
