### ISSUE TITLE
Panic when AWS AdministratorAccess policy missing

### ISSUE THREAD

**Issue by huguesalary** [goadapp/goad#6]
Your API access needs the `AdministratorAccess policy` otherwise `goad` will panic.

```
No results received
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x120acf]

goroutine 1 [running]:
github.com/gophergala2016/goad/infrastructure.(*Infrastructure).createIAMLambdaRole(0xc82007da70, 0x5882f0, 0x10, 0x0, 0x0, 0xeb2910, 0xc820498210)
        /Users/matt/Code/go/src/github.com/gophergala2016/goad/infrastructure/infrastructure.go:140 +0x55f
github.com/gophergala2016/goad/infrastructure.(*Infrastructure).setup(0xc82007da70, 0x0, 0x0)
        /Users/matt/Code/go/src/github.com/gophergala2016/goad/infrastructure/infrastructure.go:42 +0x57
github.com/gophergala2016/goad/infrastructure.New(0xc82007d7d0, 0x3, 0x3, 0xc8200a45a0, 0xa7f0e0, 0x0, 0x0)
        /Users/matt/Code/go/src/github.com/gophergala2016/goad/infrastructure/infrastructure.go:25 +0x9d
github.com/gophergala2016/goad.(*Test).Start(0xc820088060, 0x0)
        /Users/matt/Code/go/src/github.com/gophergala2016/goad/goad.go:62 +0x14b
main.start(0xc820088060, 0xc8200cbe90, 0xc820076540)
        /Users/matt/Code/go/src/github.com/gophergala2016/goad/cli/cli.go:80 +0xea
main.main()
        /Users/matt/Code/go/src/github.com/gophergala2016/goad/cli/cli.go:65 +0x606

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 20 [runnable]:
os/signal.process(0xea0050, 0xc8204de000)
        /usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal.go:173 +0xca
os/signal.loop()
        /usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:22 +0x75
created by os/signal.init.1
        /usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 21 [select, locked to thread]:
runtime.gopark(0x614480, 0xc82002bf28, 0x530c98, 0x6, 0x30d18, 0x2)
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002bf28, 0x0, 0x18)
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002bf28)
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 10 [IO wait]:
net.runtime_pollWait(0xea5c08, 0x72, 0xc8200780a0)
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201960d0, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201960d0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820196070, 0xc8204a7800, 0x400, 0x400, 0x0, 0xea0028, 0xc8200780a0)
        /usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200880d0, 0xc8204a7800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.3/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820503f50, 0xea5d18, 0xc8200880d0, 0x5, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.3/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8201922c0, 0x614517, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.3/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8201922c0, 0xc82001d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.3/libexec/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0xe61548, 0xc8201922c0, 0xc82019c058, 0xc82001d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8203b37a0, 0xc82001d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820077bc0)
        /usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820077bc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82019c000)
        /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:685 +0xc78

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc82019c000)
        /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:686 +0xc9d
```

**Comment by jcxplorer** [comment]
Thanks for the report! We have access to the repo again, so we'll look into fixing this soon! :)
